// swift-tools-version: 6.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription
import Foundation

let release = "3.1.2"
let cdnBaseURL = "https://d1st2jzonb6gjl.cloudfront.net/vesper/\(release)/spm"

//autogenerated
let xcFrameworks_ios: [(name: String, checksum: String)] = [
    ("DzAVPlayerAdapter", "1de1aaa2c004b8aacfd6f8017db4218f8e2936a9379dbf6da7d12922f53befb1"),
    ("DzBase", "babee735d970ef3dd8bf05df9a1eff1b619c749887c8a1559028388b085e10c1"),
    ("DzMediaTailorAdapter", "d61c16f2a36d47cd456882da3c8ac6c1ba86f289df4485edf85e11ea2ef6be3b"),
    ("GoogleCast", "d8b9812761efbc4a45608c96da028f32b449ee29e0270fb8ea81278becb0366e"),
    ("MediaTailorSDK", "593262f029cee1d9ffcbc03082999174e7958b66d837b03656b412af82df8e77"),
    ("OMSDK_Elemental", "14417d88bca18514f903cfd06de9505d8a2d9becfbad122937c184a5831734f1"),
    ("OMSDK_Yospace", "21253017a92f8a92bbf01d7930ff398085b93311e4dbbc87ca7c91ffaa7623e9"),
    ("ProgrammaticAccessLibrary", "b598833c3e7150002d335f8ddba02f38b408781aa5ae73fa124f77ecabd38a1a"),
    ("RxSwift", "a6c5b878e0b19def67c694cbb8e0feadb593dd8ec94cf565e088899fccffea11"),
    ("VesperPubNub", "486a1876a3fb98e788a09042d805a82ac9ef738ccb5ebfe08b2cfeba7c65e99c"),
    ("VesperSDK", "1f219536b7a9f77d09bb97b39a966cb602390fd5b10a6f45b8cf6447743b26c5"),
    ("YOAdManagement", "144161b62d2bbc95a2455f17f61e0fd9473db2945b533398b826681512cf2bc7"),
    ("YOOpenMeasurementAdapter", "05d14c57c50224a2e39171023c060cf0112df409a5c7d5523a4c32b3aa7768a2"),
]

let xcFrameworks_tvos: [(name: String, checksum: String)] = [
    ("DzAVPlayerAdapter", "45d60198b501a18a08f27db165ac25ae61b177992d103b8aaceb542251b40d5d"),
    ("DzBase", "5dcd6cbcc1dbcc8a6897bc90d7f257824aaab028dd3e3ce8feaa065399bf1ecd"),
    ("DzMediaTailorAdapter", "46852105d73369702c9b77a166efdaeaace9c421434d3f2b3d505ddf6e69bbab"),
    ("MediaTailorSDK", "81cfdd2712d97617290eb0dac20b92e3d82e86b8c9279fc66a47a4345b01c69a"),
    ("OMSDK_Elemental", "3186dfc7415e458df3425002475b1d23b4f0c585cb4d65d334d3e8585f5710a6"),
    ("ProgrammaticAccessLibrary", "5cbb2e96eff0550a5abe0f982deec395102d7a8a9e4a35df092adeec685258d7"),
    ("RxSwift", "8ff985575309f0b5905e6d0f46640a49059bde4b39ccd33d169172f61c39aada"),
    ("VesperPubNub", "0f0cbffc689a14c68953f1b21daec978e2d47eb8f78cffbb5137d8b680b00275"),
    ("VesperSDK", "6cc8bb135cbf14f58cfb60f1e0fd2abd356cda2adce50709e771b79686d56dbd"),
    ("YOAdManagement", "4b22e17715655b6ffe11c68a0fde7e8dae7016bea573ffc7b7d9518a77ed1950"),
]

let remoteBinaryTargets_ios: [Target] = xcFrameworks_ios.map { target in
    .binaryTarget(
        name: "\(target.name)_ios",
        url: "\(cdnBaseURL)/iosFrameworks/\(target.name).xcframework.zip",
        checksum: target.checksum
    )
}

let remoteBinaryTargets_tvos: [Target] = xcFrameworks_tvos.map { target in
    .binaryTarget(
        name: "\(target.name)_tvos",
        url: "\(cdnBaseURL)/tvosFrameworks/\(target.name).xcframework.zip",
        checksum: target.checksum
    )
}

let localBinaryTargets_ios: [Target] = xcFrameworks_ios.map { target in
    .binaryTarget(
        name: "\(target.name)_ios",
        path: "./iosFrameworks/\(target.name).xcframework"
    )
}

let localBinaryTargets_tvos: [Target] = xcFrameworks_tvos.map { target in
    .binaryTarget(
        name: "\(target.name)_tvos",
        path: "./tvosFrameworks/\(target.name).xcframework"
    )
}

let remoteBinaryTargets = remoteBinaryTargets_ios + remoteBinaryTargets_tvos
let localBinaryTargets = localBinaryTargets_ios + localBinaryTargets_tvos

let privateTargetDependencies_ios: [Target.Dependency] = xcFrameworks_ios.map {
    .target(name: "\($0.name)_ios", condition: .when(platforms: [.iOS]))
}
let privateTargetDependencies_tvos: [Target.Dependency] = xcFrameworks_tvos.map {
    .target(name: "\($0.name)_tvos", condition: .when(platforms: [.tvOS]))
}

let publicTargetDependencies_shared: [Target.Dependency] = [
    .product(name: "MUXSDKStats", package: "mux-stats-sdk-avplayer"),
    .product(name: "ConvivaAVFoundation", package: "conviva-ios-avfoundation-spm"),
]

let publicTargetDependencies_ios: [Target.Dependency] = [
    .product(name: "GoogleInteractiveMediaAds", package: "swift-package-manager-google-interactive-media-ads-ios", condition: .when(platforms: [.iOS])),
]

let publicTargetDependencies_tvos: [Target.Dependency] = [
    .product(name: "GoogleInteractiveMediaAdsTvOS", package: "swift-package-manager-google-interactive-media-ads-tvos", condition: .when(platforms: [.tvOS])),
]

let shouldUseLocalBinaryTargets = false
let binaryTargets = shouldUseLocalBinaryTargets ? localBinaryTargets : remoteBinaryTargets

let wrapperTarget: Target = .target(
    name: "VesperSDKWrapper",
    dependencies: privateTargetDependencies_ios + publicTargetDependencies_shared + publicTargetDependencies_ios,
    path: "Sources/VesperSDKWrapper",
    resources: [.process("Resources")]
)

let wrapperTargetTvOS: Target = .target(
    name: "VesperSDKWrapperTvOS",
    dependencies: privateTargetDependencies_tvos + publicTargetDependencies_shared + publicTargetDependencies_tvos,
    path: "Sources/VesperSDKWrapperTvOS",
    resources: [.process("Resources")]
)

let packagePlatforms: [SupportedPlatform] = [.iOS(.v15), .tvOS(.v16)]
let packageProducts: [Product] = [
    .library(name: "VesperSDK", targets: ["VesperSDKWrapper"]),
    .library(name: "VesperSDK-tvOS", targets: ["VesperSDKWrapperTvOS"]),
]
let packageDependencies_shared: [Package.Dependency] = [
    .package(url: "https://github.com/muxinc/mux-stats-sdk-avplayer", .upToNextMajor(from: "3.6.2")),
    .package(url: "https://github.com/Conviva/conviva-ios-avfoundation-spm", .upToNextMinor(from: "4.0.51")),
]

let packageDependencies_ios: [Package.Dependency] = [
    .package(url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-ios", .upToNextMajor(from: "3.22.0")),
]

let packageDependencies_tvos: [Package.Dependency] = [
    .package(url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-tvos", .upToNextMajor(from: "4.12.0")),
]

let packageDependencies: [Package.Dependency] = packageDependencies_shared + packageDependencies_ios + packageDependencies_tvos
let packageTargets = [wrapperTarget, wrapperTargetTvOS] + binaryTargets

let package = Package(
    name: "VesperSDK",
    platforms: packagePlatforms,
    products: packageProducts,
    dependencies: packageDependencies,
    targets: packageTargets
)

