// swift-tools-version: 6.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription
import Foundation

let release = "2.0.2"
let cdnBaseURL = "https://d1st2jzonb6gjl.cloudfront.net/vesper/\(release)/spm"

//autogenerated
let xcFrameworks: [(name: String, checksum: String)] = [
    ("AVDoris", "deb8e84f5194041336daa39f8ae3777c0222b447df3f2da951e2b0aa3e9b288e"),
    ("dice_shield_ios", "fef5f5d742461b18d23636774e29c7b5ce6282655bc4399b34aad3c6009dae50"),
    ("DzAVPlayerAdapter", "e49510b4190a455b7a6b541cbe9642be79996f46b25ddf4fc96079ab69a04451"),
    ("DzBase", "a6fff345972f36a1bae39d2947b48e73500f06a8e4e6f9848ba209bae01afe08"),
    ("DzMediaTailorAdapter", "0f54fa19638ed13a1949541f99b5b7d984a513623a3fef754ba042127c870e66"),
    ("GoogleCast", "86bb7c8ac389cbde1c6ccece1eed29bccf6feb5f51b8cceb9637436a5099b12c"),
    ("MediaTailorSDK", "92015f25d293916edb2dd177eb0c853346f2af080e4783eea9f2a327e9ed85b8"),
    ("OMSDK_Elemental", "190912e34e893e9134f827f8a47b8d960ed13a188e0e1603b09daf3b812127a9"),
    ("OMSDK_Yospace", "d32991bdd226b3afc002d45a503aa7abe21573fd699b3d0815e36812d18ddf8b"),
    ("ProgrammaticAccessLibrary", "89ba81a788601658e1a614fd971e8e017e6fdc658080060673c53a6d75013b14"),
    ("RxSwift", "a679a7766900a844298786f5255c0b8b2772b381b25765e7f0138ae5d33c39d0"),
    ("VesperPubNub", "739d6e0b13e89f97a0817124f111bcf80be8f31acaf1b316fc192b9f378072d6"),
    ("VesperSDK", "8d7ee61af58aecd194053515ff40bf1d9d592b79454b63da0aa6941c68dc949a"),
    ("YOAdManagement", "a45e0e3326c190c1413f266fa13694388c678bb18816078c40cc09c38d101285"),
    ("YOOpenMeasurementAdapter", "217d31aa5cf74b2a87cf553a31d7b8c21ac65efd76a59b6bdc52d98ba1982f28"),
] 

let remoteBinaryTargets: [Target] = xcFrameworks.map { target in
    return .binaryTarget(
        name: target.name,
        url: "\(cdnBaseURL)/iphoneFrameworks/\(target.name).xcframework.zip",
        checksum: target.checksum
    )
}

let localBinaryTargets: [Target] = xcFrameworks.map { target in
    .binaryTarget(
        name: target.name,
        path: "./iphoneFrameworks/\(target.name).xcframework"
    )
}

let privateTargetDependencies: [Target.Dependency] = xcFrameworks.map { Target.Dependency(stringLiteral: $0.name) }
let publicTargetDependencies: [Target.Dependency] = [
    .product(name: "MUXSDKStats", package: "mux-stats-sdk-avplayer"),
    .product(name: "GoogleInteractiveMediaAds", package: "swift-package-manager-google-interactive-media-ads-ios"),
    .product(name: "ConvivaAVFoundation", package: "conviva-ios-avfoundation-spm"),
]

let shouldUseLocalBinaryTargets = false
let binaryTargets = shouldUseLocalBinaryTargets ? localBinaryTargets : remoteBinaryTargets

let wrapperTarget: Target = .target(
    name: "VesperSDKWrapper",
    dependencies: privateTargetDependencies + publicTargetDependencies,
    resources: [.embedInCode("Resources")]
)

let packagePlatforms: [SupportedPlatform] = [.iOS(.v15)]
let packageProducts: [Product] = [.library(name: "VesperSDK", targets: ["VesperSDKWrapper"])]
let packageDependencies: [Package.Dependency] = [
    .package(url: "https://github.com/muxinc/mux-stats-sdk-avplayer", .upToNextMajor(from: "3.6.2")),
    .package(url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-ios", .upToNextMajor(from: "3.22.0")),
    .package(url: "https://github.com/Conviva/conviva-ios-avfoundation-spm", .upToNextMinor(from: "4.0.51")),
]
let packageTargets = [wrapperTarget] + binaryTargets

let package = Package(
    name: "VesperSDK",
    platforms: packagePlatforms,
    products: packageProducts,
    dependencies: packageDependencies,
    targets: packageTargets
)

