// swift-tools-version: 6.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription
import Foundation

let release = "3.0.2"
let cdnBaseURL = "https://d1st2jzonb6gjl.cloudfront.net/vesper/\(release)/spm"

//autogenerated
let xcFrameworks_ios: [(name: String, checksum: String)] = [
    ("dice_shield_ios", "0c1ec24e82cc820abda20b7247391138a50ffd9ebfdb42e2cdc406f72e38279b"),
    ("DzAVPlayerAdapter", "c16105494963ed360e05de9e3069c88a8c408acaf4de148e8da9fad38527f316"),
    ("DzBase", "c3b662b1d19f0288ee1c784f179d1af6945d7283550c29b70e203c3c84360545"),
    ("DzMediaTailorAdapter", "ec99cc9d10276fe1f00cfce0d3e3768249c4608b2014988064e28c6ecd911532"),
    ("GoogleCast", "05ba88287d21b7c57cf23c5392d63909372672e50090de9b4affe276d795e103"),
    ("MediaTailorSDK", "94d13067c19a53ce808a525aa1ec03ae4bc5ed27f121631334dc210a60dac24b"),
    ("OMSDK_Elemental", "0100c9632cbcfe618974240d32be4354afeda3eb88fad34323974d1a82cb2f8a"),
    ("OMSDK_Yospace", "e645971b53c004ca1ffef44658cb2e5abd1b4379f47b2169dae9d41d2ca43a98"),
    ("ProgrammaticAccessLibrary", "a406042e29f7a94c5af6dfc0a09da39ff5b84df7d05a7e207332cead11efa886"),
    ("RxSwift", "fb3d9c4d2b1eebdc7f3d48aa3c7d77c535335812344249739850f90b05bb95ea"),
    ("VesperPubNub", "dea820caa43be2ce8126095eac531ceea6c7fe60307fd6a59d6b726fa96c9d65"),
    ("VesperSDK", "762db998e4ae3fb129e4213b1abbc60454cc4ce39186b67846d8df4a67d922e1"),
    ("YOAdManagement", "9c39190370639f51ab5d5ba96ddcbe309de4c1f4b0957c5fa5d6c2d7d7fec033"),
    ("YOOpenMeasurementAdapter", "1fabf1be56952ef9c6362fc6f09646bab6bff7d03b7a2524584be72056dd82d3"),
]

let xcFrameworks_tvos: [(name: String, checksum: String)] = [
    ("dice_shield_ios", "4ef1247d4a216d5ec14f11a1d42fe2808f46ed1d6be21bb117e3d4190c48f5f9"),
    ("DzAVPlayerAdapter", "8d75e2ad09b0d987c1cc1766fc303be58ee3825d5dadd8c8fa4882f3d298a72b"),
    ("DzBase", "acf2ceb6c27e5a74d8c6110b69f9011a0c0f548db7d98057ee7b388ab971594e"),
    ("DzMediaTailorAdapter", "53aaba9f420e1550a17e200bb31862b8a5b1f75777b8c2d6de80a9ff66cf70f9"),
    ("MediaTailorSDK", "ddd4f5273ab7ac7f530c925ed0534c0ea261b8001e0d342a2138fadc259c8bee"),
    ("OMSDK_Elemental", "25f1d8f07c8e6afca5348d67895f25c38a2d3cdb48da56aed442d4686d575fc6"),
    ("ProgrammaticAccessLibrary", "8a0a1cbce2c3a9ebce7bf407380dd56ba04e1481d03fd4253cda65cce844978d"),
    ("RxSwift", "847490ed8f520d25b4d0effaae901c75466867ae8cc3a1e9aaf6311ae73ec291"),
    ("VesperPubNub", "05446028df5e6af83723357699ce6ebdb2e45357603b492a528155efe9c1c561"),
    ("VesperSDK", "84fdae619386e3d37d29e0cc621f1addff1ae7ded21d83d6b399383ed7d3f75c"),
    ("YOAdManagement", "1df2b0c95e15e034caca8d30f7917ad8ffc68cbfedbfc7df5bdf6ef65e37cbdf"),
]

let remoteBinaryTargets_ios: [Target] = xcFrameworks_ios.map { target in
    .binaryTarget(
        name: "\(target.name)_ios",
        url: "\(cdnBaseURL)/iosFrameworks/\(target.name).xcframework.zip",
        checksum: target.checksum
    )
}

let remoteBinaryTargets_tvos: [Target] = xcFrameworks_tvos.map { target in
    .binaryTarget(
        name: "\(target.name)_tvos",
        url: "\(cdnBaseURL)/tvosFrameworks/\(target.name).xcframework.zip",
        checksum: target.checksum
    )
}

let localBinaryTargets_ios: [Target] = xcFrameworks_ios.map { target in
    .binaryTarget(
        name: "\(target.name)_ios",
        path: "./iosFrameworks/\(target.name).xcframework"
    )
}

let localBinaryTargets_tvos: [Target] = xcFrameworks_tvos.map { target in
    .binaryTarget(
        name: "\(target.name)_tvos",
        path: "./tvosFrameworks/\(target.name).xcframework"
    )
}

let remoteBinaryTargets = remoteBinaryTargets_ios + remoteBinaryTargets_tvos
let localBinaryTargets = localBinaryTargets_ios + localBinaryTargets_tvos

let privateTargetDependencies_ios: [Target.Dependency] = xcFrameworks_ios.map {
    .target(name: "\($0.name)_ios", condition: .when(platforms: [.iOS]))
}
let privateTargetDependencies_tvos: [Target.Dependency] = xcFrameworks_tvos.map {
    .target(name: "\($0.name)_tvos", condition: .when(platforms: [.tvOS]))
}

let publicTargetDependencies_shared: [Target.Dependency] = [
    .product(name: "MUXSDKStats", package: "mux-stats-sdk-avplayer"),
    .product(name: "ConvivaAVFoundation", package: "conviva-ios-avfoundation-spm"),
]

let publicTargetDependencies_ios: [Target.Dependency] = [
    .product(name: "GoogleInteractiveMediaAds", package: "swift-package-manager-google-interactive-media-ads-ios", condition: .when(platforms: [.iOS])),
]

let publicTargetDependencies_tvos: [Target.Dependency] = [
    .product(name: "GoogleInteractiveMediaAdsTvOS", package: "swift-package-manager-google-interactive-media-ads-tvos", condition: .when(platforms: [.tvOS])),
]

let shouldUseLocalBinaryTargets = false
let binaryTargets = shouldUseLocalBinaryTargets ? localBinaryTargets : remoteBinaryTargets

let wrapperTarget: Target = .target(
    name: "VesperSDKWrapper",
    dependencies: privateTargetDependencies_ios + publicTargetDependencies_shared + publicTargetDependencies_ios,
    path: "Sources/VesperSDKWrapper",
    resources: [.process("Resources")]
)

let wrapperTargetTvOS: Target = .target(
    name: "VesperSDKWrapperTvOS",
    dependencies: privateTargetDependencies_tvos + publicTargetDependencies_shared + publicTargetDependencies_tvos,
    path: "Sources/VesperSDKWrapperTvOS",
    resources: [.process("Resources")]
)

let packagePlatforms: [SupportedPlatform] = [.iOS(.v15), .tvOS(.v16)]
let packageProducts: [Product] = [
    .library(name: "VesperSDK", targets: ["VesperSDKWrapper"]),
    .library(name: "VesperSDK-tvOS", targets: ["VesperSDKWrapperTvOS"]),
]
let packageDependencies_shared: [Package.Dependency] = [
    .package(url: "https://github.com/muxinc/mux-stats-sdk-avplayer", .upToNextMajor(from: "3.6.2")),
    .package(url: "https://github.com/Conviva/conviva-ios-avfoundation-spm", .upToNextMinor(from: "4.0.51")),
]

let packageDependencies_ios: [Package.Dependency] = [
    .package(url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-ios", .upToNextMajor(from: "3.22.0")),
]

let packageDependencies_tvos: [Package.Dependency] = [
    .package(url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-tvos", .upToNextMajor(from: "4.12.0")),
]

let packageDependencies: [Package.Dependency] = packageDependencies_shared + packageDependencies_ios + packageDependencies_tvos
let packageTargets = [wrapperTarget, wrapperTargetTvOS] + binaryTargets

let package = Package(
    name: "VesperSDK",
    platforms: packagePlatforms,
    products: packageProducts,
    dependencies: packageDependencies,
    targets: packageTargets
)

